import { Hono } from 'hono';
import { adminTicketListQuerySchema, adminTicketReplyInputSchema, errorHttpStatus, formatTicketNumber, parseWith, type HttpErrorBody, type Result } from '@remoa/contracts';
import { assignTicket, getTicket, listTickets, notifyAnswered, replyAsAdmin, resolveTicket, ticketNumberOf } from '../../support/admin-inbox';
import type { AdminEnv } from '../core/require-admin';
import { withAdmin } from '../core/with-admin';

const send = <T>(r: Result<T>) =>
  r.ok ? Response.json({ ok: true, data: r.data }) : Response.json({ error: r.error } satisfies HttpErrorBody, { status: errorHttpStatus[r.error.code] });
const notFound = () => Response.json({ error: { code: 'not_found', message: 'ticket not found' } } satisfies HttpErrorBody, { status: 404 });

// /v1/admin/tickets (mounted by routes/admin.ts behind requireAdmin). Inbox actions are routine: sensitive: false, reason generated by the server (D-432).
export const ticketsRoutes = new Hono<AdminEnv>()
  .get('/', async (c) => {
    const q = parseWith(adminTicketListQuerySchema, c.req.query());
    return send(q.ok ? await listTickets(c.get('admin').id, q.data) : q);
  })
  .get('/:id', async (c) => send(await getTicket(c.get('admin').id, c.req.param('id'))))
  .post('/:id/messages', async (c) => {
    const body = parseWith(adminTicketReplyInputSchema, await c.req.json().catch(() => null));
    if (!body.ok) return send(body);
    const id = c.req.param('id');
    const number = await ticketNumberOf(id);
    if (number === null) return notFound();
    const admin = c.get('admin').id;
    let notify: (() => Promise<void>) | null = null;
    const r = await withAdmin(c, body.data.internal ? 'ticket.internal_note' : 'ticket.reply', { reason: `Atendimento do chamado ${formatTicketNumber(number)}`, target: { type: 'ticket', id }, sensitive: false }, async (tx, audit) => {
      const x = await replyAsAdmin(tx, admin, id, body.data);
      if (!x.ok) return x;
      audit.before({ status: x.data.before });
      audit.after({ status: x.data.after, internal: x.data.internal }); // never the message text
      if (!x.data.internal) notify = () => notifyAnswered(x.data.userId, id, x.data.number);
      return { ok: true, data: {} };
    });
    if (r.ok) await (notify as (() => Promise<void>) | null)?.(); // after commit
    return send(r);
  })
  .post('/:id/assign', async (c) => action(c, 'ticket.assign', (tx, id, admin) => assignTicket(tx, admin, id)))
  .post('/:id/resolve', async (c) => action(c, 'ticket.resolve', (tx, id) => resolveTicket(tx, id)));

async function action(
  c: Parameters<typeof withAdmin>[0],
  name: 'ticket.assign' | 'ticket.resolve',
  fn: (tx: Parameters<Parameters<typeof withAdmin>[3]>[0], id: string, admin: string) => Promise<Result<{ before: string; after: string }>>,
) {
  const id = c.req.param('id') ?? '';
  const number = await ticketNumberOf(id);
  if (number === null) return notFound();
  const admin = c.get('admin').id;
  return send(
    await withAdmin(c, name, { reason: `Atendimento do chamado ${formatTicketNumber(number)}`, target: { type: 'ticket', id }, sensitive: false }, async (tx, audit) => {
      const x = await fn(tx, id, admin);
      if (!x.ok) return x;
      audit.before({ status: x.data.before });
      audit.after({ status: x.data.after });
      return { ok: true, data: {} };
    }),
  );
}
