import { describe, expect, it } from 'vitest';
import * as c from './question-admin-catalog';
import { questionSessionsListSchema } from './question-catalog';
import { mockQuestionAdminCatalogPage as page,mockQuestionVersionHistoryPage,mockQuestionReviewHistoryPage,mockQuestionSessionsPage,mockQuestionImportPage } from './mocks/question-admin-catalog';
const id='33000000-0000-4000-8000-000000000001';
const audit={id:1,createdAt:'2026-10-09T00:00:00Z',actorType:'admin',actor:null,action:'question.catalog_view',targetType:'route',targetId:'/v1/admin/questions/catalog',targetLabel:null,reason:'Consultar catálogo administrativo',result:'success',denial:null,before:null,after:null,ipHash:null,userAgent:null,requestId:null};
describe('CCR139 metadata discovery',()=>{
 it('keeps explicit defaults and legacy sessions',()=>{expect(c.questionAdminCatalogQuerySchema.parse({})).toEqual({versions:'latest',limit:25});expect(c.questionImportPageQuerySchema.parse({}).limit).toBe(25);expect(c.questionHistoryQuerySchema.parse({}).limit).toBe(25);expect(c.questionSessionsPageQuerySchema.parse({}).limit).toBe(20);expect(questionSessionsListSchema.safeParse(mockQuestionSessionsPage.items).success).toBe(true);});
 it.each([c.questionAdminCatalogQuerySchema,c.questionImportPageQuerySchema,c.questionHistoryQuerySchema,c.questionSessionsPageQuerySchema])('rejects duplicates and invalid URL values',s=>{for(const v of [{limit:['20','25']},{cursor:['x','y']},{cursor:''},{cursor:' '},{cursor:'x'.repeat(2049)},{limit:''},{limit:'0'},{limit:null},{unexpected:true}])expect(s.safeParse(v).success).toBe(false);});
 it('coerces URL limits but validates all filters',()=>{expect(c.questionAdminCatalogQuerySchema.parse({limit:'50',search:' título ',versions:'all',status:'withdrawn'}).search).toBe('título');for(const v of [{status:''},{search:''},{sourceId:''},{versions:'unknown'},{status:['draft','published']},{limit:'51'},{search:'x'.repeat(201)}])expect(c.questionAdminCatalogQuerySchema.safeParse(v).success).toBe(false);expect(c.questionSessionsPageQuerySchema.safeParse({limit:'21'}).success).toBe(false);});
 it.each(['correctKey','explanation','assets','raw','objectKey','userId','reviewerUserId'])('forbids leakage %s',field=>expect(c.questionAdminCatalogItemSchema.safeParse({...page.items[0],[field]:'private'}).success).toBe(false));
 it('separates audited admin and editorial payloads',()=>{expect(c.questionAdminCatalogResultSchema.safeParse({...page,audit}).success).toBe(true);expect(c.questionAdminCatalogResultSchema.safeParse(page).success).toBe(false);expect(c.questionAdminCatalogPageSchema.safeParse({...page,audit}).success).toBe(false);});
 it('rejects page and preview overflow without truncation',()=>{expect(c.questionAdminCatalogPageSchema.safeParse({items:Array(50).fill(page.items[0]),nextCursor:'opaque'}).success).toBe(true);expect(c.questionAdminCatalogPageSchema.safeParse({items:Array(51).fill(page.items[0]),nextCursor:null}).success).toBe(false);expect(c.questionAdminCatalogItemSchema.safeParse({...page.items[0],stemPreview:'x'.repeat(301)}).success).toBe(false);expect(c.questionSessionsPageResultSchema.safeParse({items:Array(21).fill(mockQuestionSessionsPage.items[0]),nextCursor:null}).success).toBe(false);});
 it.each([null,0,'invalid','2026-02-31'])('rejects malformed dates %s',createdAt=>expect(c.questionAdminCatalogItemSchema.safeParse({...page.items[0],createdAt}).success).toBe(false));
 it('validates signed history without exposing reviewer ids',()=>{const row={id,questionId:id,decision:'changes_requested',contentHash:'a'.repeat(64),reason:'Solicitar conferência sintética',reviewerName:'Nome sintético',reviewerCrm:'SP-12345',referenceDate:'2024-02-29',reviewedAt:'2026-10-09T00:00:00Z'};expect(c.questionReviewHistoryItemSchema.parse(row).reason).toBe(row.reason);for(const p of [{referenceDate:'2023-02-29'},{referenceDate:'2024-13-01'},{reviewerUserId:id},{contentHash:'A'.repeat(64)}])expect(c.questionReviewHistoryItemSchema.safeParse({...row,...p}).success).toBe(false);});
 it('validates all synthetic mocks',()=>{expect(c.questionImportPageResultSchema.safeParse(mockQuestionImportPage).success).toBe(true);expect(c.questionVersionHistoryPageSchema.safeParse(mockQuestionVersionHistoryPage).success).toBe(true);expect(c.questionReviewHistoryPageSchema.safeParse(mockQuestionReviewHistoryPage).success).toBe(true);expect(c.questionSessionsPageResultSchema.safeParse(mockQuestionSessionsPage).success).toBe(true);});
});
