import { beforeEach,describe,expect,it,vi } from 'vitest';
import { PgDialect } from 'drizzle-orm/pg-core';
import type { Tx } from '@remoa/db';
import { questionAdminCatalogQuerySchema,questionHistoryQuerySchema } from '@remoa/contracts';
import { catalogPageSQL,catalogPage,catalogStaff,catalogQueryValues,encodeCatalogCursor,decodeCatalogCursor,versionHistory,reviewHistory,type CatalogCursorScope } from './catalog';
const id='33000000-0000-4000-8000-000000000001',second='33000000-0000-4000-8000-000000000002';
const actor={id,role:'reviewer' as const};
const at='2026-10-09T12:00:00.123456Z';
const dialect=new PgDialect();
const row=(qid=id)=>({id:qid,canonicalId:id,supersedesId:null,version:1,type:'objective',origin:'official_exam',stemPreview:'Sintético',catalogStatus:'withdrawn',rightsStatus:'revoked',availability:'active',sourceId:null,sourceLabel:null,contentHash:'a'.repeat(64),reviewedHash:'a'.repeat(64),createdAt:'2026-10-09T12:00:00Z',updatedAt:'2026-10-09T12:00:00Z',publishedAt:null,cursorAt:at,correctKey:'E',assets:[{objectKey:'private'}]});
const fake=(...results:unknown[][])=>{const execute=vi.fn();results.forEach(r=>execute.mockResolvedValueOnce(r));return {tx:{execute} as unknown as Tx,execute};};
beforeEach(()=>{process.env.SHARE_SECRET='synthetic-catalog-test-secret';});
describe('CCR139 cursor and query semantics',()=>{
 it('rejects foreign user, role, route, filters and tampered cursors',()=>{const query=questionAdminCatalogQuerySchema.parse({status:'withdrawn'}),scope:CatalogCursorScope={actor,route:'/editorial/questions/catalog',query};const cur=encodeCatalogCursor(at,id,scope);expect(decodeCatalogCursor(cur,scope)).toEqual({at,id});for(const foreign of [{...scope,actor:{...actor,id:second}},{...scope,actor:{...actor,role:'admin' as const}},{...scope,route:'/admin/questions/catalog'},{...scope,query:{...query,status:'published'}}])expect(decodeCatalogCursor(cur,foreign)).toBeNull();expect(decodeCatalogCursor(cur+'x',scope)).toBeNull();expect(decodeCatalogCursor('x.y.z',scope)).toBeNull();});
 it('preserves duplicate query keys and rejects them rather than collapse',()=>{const q=catalogQueryValues('https://api.example/catalog?limit=25&limit=50&status=withdrawn');expect(q.limit).toEqual(['25','50']);expect(questionAdminCatalogQuerySchema.safeParse(q).success).toBe(false);expect(questionAdminCatalogQuerySchema.safeParse(catalogQueryValues('https://api.example/catalog?ownerId='+id)).success).toBe(false);});
 it('uses institutional projection, deterministic keyset and bounded latest selection',()=>{const built=dialect.sqlToQuery(catalogPageSQL(questionAdminCatalogQuerySchema.parse({search:'50%_x',limit:2}),{at,id}));expect(built.sql).toContain("q.visibility='public' AND q.user_id IS NULL");expect(built.sql).toContain('NOT EXISTS');expect(built.sql).toContain('q.created_at DESC,q.id DESC');expect(built.params).toContain(3);expect(built.params).toContain('%50\\%\\_x%');expect(built.params.filter(v=>v==='\\')).toHaveLength(2);expect(built.sql).not.toMatch(/q\.(correct_key|assets|explanation)|SELECT \*/i);});
 it('all-version mode keeps drafts and archived versions discoverable, without selection authority',()=>{expect(dialect.sqlToQuery(catalogPageSQL(questionAdminCatalogQuerySchema.parse({versions:'all',status:'draft'}),null)).sql).not.toContain('NOT EXISTS');});
});
describe('CCR139 metadata readers',()=>{
 it('projects fields, emits cursor from last returned row and avoids N+1',async()=>{const f=fake([row(),row(second),row('33000000-0000-4000-8000-000000000003')]);const query=questionAdminCatalogQuerySchema.parse({limit:2});const r=await catalogPage(f.tx,actor,query,'catalog');expect(r.ok).toBe(true);if(!r.ok)return;expect(r.data.items).toHaveLength(2);expect(r.data.items[0]).not.toHaveProperty('correctKey');expect(r.data.items[0]).not.toHaveProperty('assets');expect(decodeCatalogCursor(r.data.nextCursor!,{actor,route:'catalog',query})).toEqual({at,id:second});expect(f.execute).toHaveBeenCalledTimes(1);});
 it('bounds Unicode preview using the contract wire length',async()=>{const f=fake([{...row(),stemPreview:'🙂'.repeat(300),sourceLabel:'🙂'.repeat(300)}]);const r=await catalogPage(f.tx,actor,questionAdminCatalogQuerySchema.parse({}),'catalog');expect(r.ok).toBe(true);if(r.ok){expect(r.data.items[0]!.stemPreview.length).toBe(300);expect(r.data.items[0]!.sourceLabel?.length).toBe(300);}});
 it('returns terminal empty page and rejects invalid cursor before database access',async()=>{const f=fake([]);const r=await catalogPage(f.tx,actor,questionAdminCatalogQuerySchema.parse({}),'catalog');expect(r).toEqual({ok:true,data:{items:[],nextCursor:null}});const bad=await catalogPage(f.tx,actor,questionAdminCatalogQuerySchema.parse({cursor:'invalid'}),'catalog');expect(bad.ok).toBe(false);expect(f.execute).toHaveBeenCalledTimes(1);});
 it.each(['student',null,'reviewer'])('rechecks current admin role %s',async role=>{const f=fake(role?[{role}]:[]);expect(await catalogStaff(f.tx,id,'admin')).toBeNull();expect(dialect.sqlToQuery(f.execute.mock.calls[0]![0]).sql).toContain('deleted_at IS NULL AND suspended_at IS NULL FOR SHARE');});
 it('keeps historical version query within selected institutional canonical root',async()=>{const f=fake([{id,canonicalId:id}],[row(second)]);const r=await versionHistory(f.tx,actor,id,questionHistoryQuerySchema.parse({}),'history/'+id);expect(r.ok).toBe(true);expect(f.execute).toHaveBeenCalledTimes(2);const q=dialect.sqlToQuery(f.execute.mock.calls[1]![0]);expect(q.sql).toContain('coalesce(q.canonical_id,q.id)=');expect(q.params).toContain(id);expect(q.sql).toContain("q.visibility='public' AND q.user_id IS NULL");});
 it('private or missing root has identical not-found response without fetching history',async()=>{const f=fake([]);expect(await versionHistory(f.tx,actor,id,questionHistoryQuerySchema.parse({}),'history')).toEqual({ok:false,error:{code:'not_found',message:'question not found'}});expect(f.execute).toHaveBeenCalledTimes(1);});
 it('reads signed history without joining current reviewer identity or updating content',async()=>{const signed={id:second,questionId:id,decision:'approved',contentHash:'a'.repeat(64),reason:'Conferência sintética para testes',reviewerName:'Revisor histórico sintético',reviewerCrm:'SP-12345',referenceDate:'2024-02-29',reviewedAt:at,cursorAt:at,reviewerId:second};const f=fake([{id,canonicalId:id}],[signed]);const r=await reviewHistory(f.tx,actor,id,questionHistoryQuerySchema.parse({}),'reviews/'+id);expect(r.ok).toBe(true);if(r.ok){expect(r.data.items[0]!.reviewerName).toBe(signed.reviewerName);expect(r.data.items[0]).not.toHaveProperty('reviewerId');}const q=dialect.sqlToQuery(f.execute.mock.calls[1]![0]);expect(q.sql).not.toMatch(/profiles|\bUPDATE\b|correct_key|assets/i);expect(q.sql).toContain('r.reviewed_at DESC,r.id DESC');});
});
