// CCR124: session payload_public is API/server-only (migration0048); direct grants expose safe metadata only.
/** F33. Content versions use question_bank.supersedes_id; there is no second version chain. */
import { sql } from 'drizzle-orm';
import { boolean, check, foreignKey, index, integer, jsonb, pgTable, text, timestamp, unique, uuid } from 'drizzle-orm/pg-core';
import { questionImportStatuses, questionRightsStatuses, questionCandidateStatuses, type QuestionPublic, type QuestionSessionConfig, type QuestionProvenance } from '@remoa/contracts';
import { timestamps, userId,authUsers } from './common';
// Institutional operation identities are attribution, never ownership of the institutional asset.
const institutionalActor=()=>uuid('user_id').references(()=>authUsers.id,{onDelete:'set null'});
import { questionBank } from './challenge-ai';
const id = () => uuid('id').primaryKey().defaultRandom();
const json = (name: string) => jsonb(name).$type<Record<string, unknown>>();
const enumCheck = (name: string, column: string, values: readonly string[]) => check(name, sql.raw(`${column} in (${values.map((x) => `'${x}'`).join(',')})`));
export const questionSourcesCatalog = pgTable('question_sources', {
  id: id(), name: text('name').notNull(), publisher: text('publisher').notNull(), url: text('url').notNull(),
  rightsStatus: text('rights_status', { enum: questionRightsStatuses }).notNull().default('pending'), rightsEvidence: text('rights_evidence'), rightsScope: text('rights_scope'), rightsExpiresAt: timestamp('rights_expires_at', { withTimezone: true }), accessedAt: timestamp('accessed_at', { withTimezone: true }).notNull().defaultNow(), documentVersion: text('document_version'), ...timestamps,
}, (t) => [enumCheck('question_sources_rights_chk', 'rights_status', questionRightsStatuses), check('question_sources_evidence_chk', sql`${t.rightsStatus} <> 'authorized' or nullif(btrim(${t.rightsEvidence}), '') is not null`)]);
export const questionDocuments = pgTable('question_documents', {
  id: id(), actorId: institutionalActor(), sourceId: uuid('source_id').notNull().references(() => questionSourcesCatalog.id), kind: text('kind').notNull(), objectKey: text('object_key').notNull(), sha256: text('sha256').notNull(), bytes: integer('bytes').notNull(), pages: integer('pages'), mime: text('mime').notNull().default('application/pdf'), ...timestamps,
}, (t) => [index('question_documents_actor_idx').on(t.actorId), index('question_documents_source_hash_idx').on(t.sourceId, t.sha256), check('question_documents_limits_chk', sql`${t.bytes} between 1 and 104857600 and (${t.pages} is null or ${t.pages} between 1 and 500)`)]);
export const examPapers = pgTable('exam_papers', {
  id: id(), sourceId: uuid('source_id').notNull().references(() => questionSourcesCatalog.id), documentId: uuid('document_id').references(() => questionDocuments.id), answerKeyDocumentId: uuid('answer_key_document_id').references(() => questionDocuments.id), name: text('name').notNull(), institution: text('institution').notNull(), year: integer('year').notNull(), edition: text('edition').notNull(), booklet: text('booklet').notNull(), version: integer('version').notNull().default(1), durationSec: integer('duration_sec'), status: text('status').notNull().default('draft'), keyFinal: boolean('key_final').notNull().default(false), keyRevision: text('key_revision'), ...timestamps,
}, (t) => [index('exam_papers_source_idx').on(t.sourceId), index('exam_papers_document_idx').on(t.documentId), index('exam_papers_key_document_idx').on(t.answerKeyDocumentId), index('exam_papers_status_year_idx').on(t.status, t.year), unique('exam_papers_edition_booklet_version_uq').on(t.sourceId, t.edition, t.booklet, t.version), check('exam_papers_status_chk', sql`${t.status} in ('draft','published','withdrawn')`)]);
export const examQuestionOccurrences = pgTable('exam_question_occurrences', {
  id: id(), paperId: uuid('paper_id').notNull().references(() => examPapers.id, { onDelete: 'cascade' }), questionId: uuid('question_id').notNull().references(() => questionBank.id), ordinal: integer('ordinal').notNull(), originalNumber: text('original_number').notNull(), originalKeys: json('original_keys'), keyRevision: text('key_revision'), annulled: boolean('annulled').notNull().default(false), provenance: jsonb('provenance').$type<zProvenance>().notNull().default([]), ...timestamps,
}, (t) => [unique('exam_occurrences_paper_number_uq').on(t.paperId, t.originalNumber), unique('exam_occurrences_paper_ordinal_uq').on(t.paperId, t.ordinal), index('exam_occurrences_question_idx').on(t.questionId)]);
type zProvenance = QuestionProvenance[];
export const questionImports = pgTable('question_imports', {
  revision: integer('revision').notNull().default(0),
  /** Immutable original key-page scope. Custom validation/immutability triggers live in migration0051. */
  answerKeyPages: integer('answer_key_pages').array(),
  id: id(), actorId: institutionalActor(), sourceId: uuid('source_id').notNull().references(() => questionSourcesCatalog.id), paperId: uuid('paper_id').references(() => examPapers.id), documentId: uuid('document_id').notNull().references(() => questionDocuments.id), answerKeyDocumentId: uuid('answer_key_document_id').references(() => questionDocuments.id), idempotencyKey: text('idempotency_key').notNull(), parserVersion: text('parser_version').notNull(), ocrVersion: text('ocr_version'), ocrEnabled: boolean('ocr_enabled').notNull().default(true), excludedPages: jsonb('excluded_pages').$type<number[]>().notNull().default([]), status: text('status', { enum: questionImportStatuses }).notNull().default('queued'), totalPages: integer('total_pages').notNull().default(0), completedPages: integer('completed_pages').notNull().default(0), budgetCents: integer('budget_cents').notNull().default(0), costCents: integer('cost_cents').notNull().default(0), reservationId: uuid('reservation_id'), leaseUntil: timestamp('lease_until', { withTimezone: true }), workerId: text('worker_id'), attempts: integer('attempts').notNull().default(0), errorCode: text('error_code'), ...timestamps,
}, (t) => [check('question_imports_answer_key_pages_chk',sql`${t.answerKeyPages} is null or (${t.answerKeyDocumentId} is not null and public.f33_valid_answer_key_pages(${t.answerKeyPages}))`), check('question_imports_revision_chk',sql`${t.revision} >= 0`), unique('question_imports_actor_key_uq').on(t.actorId, t.idempotencyKey), index('question_imports_poll_idx').on(t.status, t.leaseUntil), index('question_imports_source_idx').on(t.sourceId), index('question_imports_paper_idx').on(t.paperId), index('question_imports_document_idx').on(t.documentId), index('question_imports_key_document_idx').on(t.answerKeyDocumentId), enumCheck('question_imports_status_chk', 'status', questionImportStatuses), check('question_imports_budget_chk', sql`${t.budgetCents} >= 0 and ${t.costCents} between 0 and ${t.budgetCents}`)]);
export const questionImportChunks = pgTable('question_import_chunks', {
  id: id(), importId: uuid('import_id').notNull().references(() => questionImports.id, { onDelete: 'cascade' }), documentId: uuid('document_id').notNull().references(() => questionDocuments.id), parserVersion: text('parser_version').notNull(), firstPage: integer('first_page').notNull(), lastPage: integer('last_page').notNull(), status: text('status').notNull().default('queued'), payloadObjectKey: text('payload_object_key'), attempts: integer('attempts').notNull().default(0), leaseUntil: timestamp('lease_until', { withTimezone: true }), workerId: text('worker_id'), errorCode: text('error_code'), ...timestamps,
}, (t) => [unique('question_chunks_document_version_pages_uq').on(t.documentId, t.parserVersion, t.firstPage, t.lastPage), index('question_chunks_import_idx').on(t.importId), index('question_chunks_poll_idx').on(t.status, t.leaseUntil), check('question_chunks_pages_chk', sql`${t.firstPage} > 0 and ${t.lastPage} >= ${t.firstPage} and ${t.lastPage} - ${t.firstPage} < 10`)]);
/** CCR130 private staging evidence; lock import → paper → contexts(id) → candidates(id) → questions(id). */
export const questionImportContexts = pgTable('question_import_contexts', {
  id:id(),importId:uuid('import_id').notNull().references(()=>questionImports.id,{onDelete:'cascade'}),
  documentId:uuid('document_id').notNull().references(()=>questionDocuments.id),
  evidenceHash:text('evidence_hash').notNull(),evidenceObjectKey:text('evidence_object_key').notNull(),
  originalText:text('original_text'),declaredNumbers:jsonb('declared_numbers').$type<number[]>().notNull().default([]),
  provenance:jsonb('provenance').$type<zProvenance>().notNull().default([]),imageRefs:jsonb('image_refs').$type<Record<string,unknown>[]>().notNull().default([]),
  revision:integer('revision').notNull().default(0),status:text('status',{enum:['unresolved','bound','non_question']}).notNull().default('unresolved'),
  resolution:json('resolution'),resolutionHash:text('resolution_hash'),...timestamps,
},t=>[
  unique('question_contexts_import_evidence_uq').on(t.importId,t.evidenceHash),
  index('question_contexts_document_idx').on(t.documentId),index('question_contexts_import_status_idx').on(t.importId,t.status),
  check('question_contexts_revision_chk',sql`${t.revision} >= 0`),
  check('question_contexts_status_chk',sql`${t.status} in ('unresolved','bound','non_question')`),
  check('question_contexts_hash_chk',sql`${t.evidenceHash} ~ '^[a-f0-9]{64}$' and (${t.resolutionHash} is null or ${t.resolutionHash} ~ '^[a-f0-9]{64}$')`),
  check('question_contexts_key_chk',sql`${t.evidenceObjectKey} like 'questions/imports/' || ${t.importId}::text || '/contexts/%'`),
  check('question_contexts_json_chk',sql`jsonb_typeof(${t.declaredNumbers})='array' and jsonb_typeof(${t.provenance})='array' and jsonb_typeof(${t.imageRefs})='array' and (${t.resolution} is null or jsonb_typeof(${t.resolution})='object')`),
  check('question_contexts_resolution_chk',sql`(${t.status} = 'unresolved' or (${t.resolution} is not null and ${t.resolutionHash} is not null)) and (${t.status} <> 'bound' or ${t.resolution}->>'decision' IS NOT DISTINCT FROM 'bind') and (${t.status} <> 'non_question' or ${t.resolution}->>'decision' IS NOT DISTINCT FROM 'non_question') and (${t.status} <> 'unresolved' or (${t.resolution} is null and ${t.resolutionHash} is null))`),
]).enableRLS();
export const questionImportCandidates = pgTable('question_import_candidates', {
  id: id(), importId: uuid('import_id').notNull().references(() => questionImports.id, { onDelete: 'cascade' }), chunkId: uuid('chunk_id').references(() => questionImportChunks.id), ordinal: integer('ordinal').notNull(), originalNumber: text('original_number'), payload: json('payload').notNull(), confidence: json('confidence').notNull().default({}), provenance: jsonb('provenance').$type<zProvenance>().notNull().default([]), issues: text('issues').array().notNull().default([]), fingerprint: text('fingerprint'), duplicateOf: uuid('duplicate_of').references(() => questionBank.id), questionId: uuid('question_id').references(() => questionBank.id), state: text('state', { enum: questionCandidateStatuses }).notNull().default('pending'), revision: integer('revision').notNull().default(0), ...timestamps,
}, (t) => [unique('question_candidates_import_ordinal_uq').on(t.importId, t.ordinal), index('question_candidates_chunk_idx').on(t.chunkId), index('question_candidates_duplicate_idx').on(t.duplicateOf), index('question_candidates_question_idx').on(t.questionId), index('question_candidates_fingerprint_idx').on(t.fingerprint), enumCheck('question_candidates_state_chk', 'state', questionCandidateStatuses)]);
export const questionGenerationRuns = pgTable('question_generation_runs', {
  id: id(), userId: userId(), producer: text('producer').notNull(), requestKey: text('request_key').notNull(), promptId: text('prompt_id').notNull(), promptVersion: text('prompt_version').notNull(), boardId: uuid('board_id'), boardVersion: integer('board_version'), model: text('model').notNull(), provider: text('provider').notNull(), payloadObjectKey: text('payload_object_key'), payloadHash: text('payload_hash'), status: text('status').notNull().default('received'), receivedCount: integer('received_count').notNull().default(0), costCents: integer('cost_cents').notNull().default(0), errorCode: text('error_code'), receivedAt: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(), ...timestamps,
}, (t) => [unique('question_runs_owner_request_uq').on(t.userId, t.producer, t.requestKey), index('question_runs_reconcile_idx').on(t.status, t.createdAt)]);
// question_id NO ACTION is DEFERRABLE INITIALLY DEFERRED in0045 (Drizzle omits deferrability).
export const questionGenerationCandidates = pgTable('question_generation_candidates', {
  id: id(), runId: uuid('run_id').notNull().references(() => questionGenerationRuns.id, { onDelete: 'cascade' }), ordinal: integer('ordinal').notNull(), payloadObjectKey: text('payload_object_key').notNull(), state: text('state', { enum: questionCandidateStatuses }).notNull().default('pending'), reasonCode: text('reason_code'), questionId: uuid('question_id').references(() => questionBank.id), ...timestamps,
}, (t) => [unique('question_generation_candidates_run_ordinal_uq').on(t.runId, t.ordinal), index('question_generation_candidates_question_idx').on(t.questionId), enumCheck('question_generation_candidates_state_chk', 'state', questionCandidateStatuses)]);
export const questionOutbox = pgTable('question_outbox', {
  id: id(), runId: uuid('run_id').references(() => questionGenerationRuns.id, { onDelete: 'cascade' }), importId: uuid('import_id').references(() => questionImports.id, { onDelete: 'cascade' }), eventKey: text('event_key').notNull().unique(), target: text('target').notNull(), payloadReference: text('payload_reference').notNull(), attempts: integer('attempts').notNull().default(0), leaseUntil: timestamp('lease_until', { withTimezone: true }), workerId: text('worker_id'), deliveredAt: timestamp('delivered_at', { withTimezone: true }), errorCode: text('error_code'), ...timestamps,
}, (t) => [index('question_outbox_poll_idx').on(t.deliveredAt, t.leaseUntil), index('question_outbox_run_idx').on(t.runId), index('question_outbox_import_idx').on(t.importId)]);
export const questionEditorialReviews = pgTable('question_editorial_reviews', {
  id: id(), questionId: uuid('question_id').notNull().references(() => questionBank.id, { onDelete: 'cascade' }), reviewerId: institutionalActor(), reviewerName: text('reviewer_name').notNull(), reviewerCrm: text('reviewer_crm').notNull(), contentHash: text('content_hash').notNull(), decision: text('decision').notNull(), reason: text('reason').notNull(), referenceDate: text('reference_date').notNull(), reviewedAt: timestamp('reviewed_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index('question_editorial_question_hash_idx').on(t.questionId, t.contentHash), index('question_editorial_reviewer_idx').on(t.reviewerId), check('question_editorial_decision_chk', sql`${t.decision} in ('approved','changes_requested','rejected')`), check('question_editorial_identity_chk', sql`length(btrim(${t.reviewerName})) > 0 and length(btrim(${t.reviewerCrm})) > 0 and length(btrim(${t.reason})) >= 8`)]);
export const questionSessions = pgTable('question_sessions', {
  id: id(), userId: userId(), mode: text('mode').notNull(), paperId: uuid('paper_id').references(() => examPapers.id), config: jsonb('config').$type<QuestionSessionConfig>().notNull(), status: text('status').notNull().default('active'), revision: integer('revision').notNull().default(0), idempotencyKey: text('idempotency_key').notNull(), startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(), deadline: timestamp('deadline', { withTimezone: true }), finishedAt: timestamp('finished_at', { withTimezone: true }), report: json('report'), ...timestamps,
}, (t) => [unique('question_sessions_id_user_uq').on(t.id, t.userId), unique('question_sessions_owner_key_uq').on(t.userId, t.idempotencyKey), index('question_sessions_paper_idx').on(t.paperId), index('question_sessions_owner_created_idx').on(t.userId, t.createdAt), check('question_sessions_mode_chk', sql`${t.mode} in ('study','simulation')`), check('question_sessions_status_chk', sql`${t.status} in ('active','finished','expired')`)]);
// question_id NO ACTION is DEFERRABLE INITIALLY DEFERRED in0045 for a whole-owner auth cascade.
export const questionSessionItems = pgTable('question_session_items', {
  id: id(), userId: userId(), sessionId: uuid('session_id').notNull(), questionId: uuid('question_id').notNull().references(() => questionBank.id), position: integer('position').notNull(), originalNumber: text('original_number'), payloadPublic: jsonb('payload_public').$type<QuestionPublic>().notNull(), referenceSnapshot: json('reference_snapshot').notNull(), shuffleMap: json('shuffle_map'), selectedKey: text('selected_key'), doubtful: boolean('doubtful').notNull().default(false), answered: boolean('answered').notNull().default(false), revision: integer('revision').notNull().default(0), ...timestamps,
}, (t) => [foreignKey({ columns: [t.sessionId, t.userId], foreignColumns: [questionSessions.id, questionSessions.userId], name: 'question_items_session_owner_fk' }).onDelete('cascade'), unique('question_items_id_session_owner_uq').on(t.id, t.sessionId, t.userId), unique('question_items_session_position_uq').on(t.sessionId, t.position), index('question_items_owner_idx').on(t.userId), index('question_items_question_idx').on(t.questionId)]);
export const questionAnswers = pgTable('question_answers', {
  id: id(), userId: userId(), sessionId: uuid('session_id').notNull(), itemId: uuid('item_id').notNull(), mutationId: uuid('mutation_id').notNull(), selectedKey: text('selected_key'), correct: boolean('correct'), elapsedMs: integer('elapsed_ms').notNull(), revision: integer('revision').notNull(), submittedAt: timestamp('submitted_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [foreignKey({ columns: [t.itemId, t.sessionId, t.userId], foreignColumns: [questionSessionItems.id, questionSessionItems.sessionId, questionSessionItems.userId], name: 'question_answers_item_owner_fk' }).onDelete('cascade'), unique('question_answers_item_mutation_uq').on(t.itemId, t.mutationId), index('question_answers_owner_submitted_idx').on(t.userId, t.submittedAt), index('question_answers_session_idx').on(t.sessionId)]);
export const questionUserState = pgTable('question_user_state', {
  id: id(), userId: userId(), questionId: uuid('question_id').notNull().references(() => questionBank.id, { onDelete: 'cascade' }), favorite: boolean('favorite').notNull().default(false), doubtful: boolean('doubtful').notNull().default(false), annotation: text('annotation').notNull().default(''), lastAnswerId: uuid('last_answer_id').references(() => questionAnswers.id, { onDelete: 'set null' }), ...timestamps,
}, (t) => [unique('question_user_state_owner_question_uq').on(t.userId, t.questionId), index('question_user_state_question_idx').on(t.questionId), index('question_user_state_answer_idx').on(t.lastAnswerId)]);
export const questionReports = pgTable('question_reports', {
  id: id(), userId: userId(), questionId: uuid('question_id').notNull().references(() => questionBank.id, { onDelete: 'cascade' }), version: integer('version').notNull(), type: text('type').notNull(), description: text('description').notNull(), status: text('status').notNull().default('open'), ...timestamps,
}, (t) => [index('question_reports_owner_idx').on(t.userId), index('question_reports_question_idx').on(t.questionId)]);
