// Unica fonte de texto dos e-mails (namespace `emails`, pt-BR). Interpolacao: {variavel}.
// O backend nao importa @remoa/strings (outro repo); manter alinhado com o namespace `emails` de la.
export const emails = {
  brand: 'remoa',
  footer: {
    transactional: 'Você recebeu este e-mail porque tem uma conta no Remoa. Dúvidas? Responda esta mensagem ou fale com o suporte dentro do app.',
    reminder: 'Você recebeu este lembrete porque ativou avisos no Remoa.',
    list: 'Você recebeu este e-mail porque entrou na lista de espera da Loja de mapas.',
    manage: 'Gerenciar notificações',
    stop: 'Parar de receber este tipo de e-mail',
    leaveList: 'Sair da lista',
  },
  accountConfirm: {
    subject: 'Confirme seu e-mail e comece no Remoa',
    preheader: 'Falta só um clique para criar seu primeiro mapa.',
    title: 'Bem-vindo ao Remoa, {name}.',
    titleNoName: 'Bem-vindo ao Remoa.',
    body: 'Sua conta está criada. Confirme seu e-mail para começar a montar mapas de estudo, revisar na hora certa e organizar suas provas.',
    button: 'Confirmar meu e-mail',
    linkNote: 'O link vale por {expires}. Se o botão não funcionar, copie este endereço no navegador:',
    stepsTitle: 'Depois disso, em 3 passos',
    steps: [
      { title: 'Crie um mapa', text: 'Do zero, de um PDF ou do seu Anki.' },
      { title: 'Revise o que vence', text: 'A fila do dia aparece na tela Hoje.' },
      { title: 'Marque suas provas', text: 'No Calendário, com aviso por e-mail.' },
    ],
    notYou: 'Não foi você? Ignore este e-mail e a conta não será ativada.',
    changePreheader: 'Falta só um clique para confirmar o novo endereço.',
    changeTitle: 'Confirme seu novo e-mail, {name}.',
    changeTitleNoName: 'Confirme seu novo e-mail.',
    changeBody: 'Você pediu para trocar o e-mail da sua conta. Confirme o novo endereço para concluir a troca.',
    changeNotYou: 'Não foi você? Ignore este e-mail e o endereço da conta continua o mesmo.',
    // CCR-037 (D-796): link de entrada sem senha (magic link do Supabase).
    magicSubject: 'Seu link para entrar no Remoa',
    magicPreheader: 'Toque no link para entrar sem senha.',
    magicTitle: 'Entre no Remoa, {name}.',
    magicTitleNoName: 'Entre no Remoa.',
    magicBody: 'Você pediu um link para entrar sem senha. Toque no botão para continuar de onde parou.',
    magicButton: 'Entrar no Remoa',
    magicNotYou: 'Não foi você? Ignore este e-mail. Ninguém entra na sua conta sem este link.',
  },
  // Página do descadastro (GET/POST /v1/emails/unsubscribe). Sem dado pessoal: só o tipo de aviso.
  unsubscribe: {
    pageTitle: 'Remoa · E-mails',
    confirm: 'Parar de receber {what}?',
    button: 'Parar de receber',
    done: 'Pronto. Você não vai mais receber {what}.',
    doneHint: 'Dá para mudar isso a qualquer momento em Notificações, no app.',
    manage: 'Abrir preferências de notificação',
    invalid: 'Este link de descadastro não é válido. Abra as preferências de notificação no app para escolher o que receber.',
    what: {
      calendar_d1: 'os lembretes de compromisso na véspera',
      calendar_d0: 'os lembretes de compromisso no dia',
      review_reminder: 'o lembrete diário de revisão',
      map_ready: 'os avisos de mapa pronto',
      inactivity: 'os lembretes de quando você some',
      referral: 'os avisos de indicação',
      support: 'os avisos de suporte',
      account_billing: 'os avisos de conta e cobrança',
      store: 'os e-mails da lista de espera da Loja',
      pause: 'e-mails de lembrete (pausa geral)',
      referral_invite: 'convites para o Remoa',
      landing_waitlist: 'os e-mails da lista de espera do Remoa',
    },
  },
  purchase: {
    subject: 'Pagamento confirmado: {plan}',
    preheader: 'Seu plano {plan} já está ativo. Veja o comprovante.',
    title: 'Pagamento confirmado.',
    body: 'Obrigado, {name}. Seu plano {plan} já está ativo e todos os benefícios foram liberados na sua conta.',
    bodyNoName: 'Obrigado. Seu plano {plan} já está ativo e todos os benefícios foram liberados na sua conta.',
    methods: { pix: 'Pix', card: 'Cartão de crédito' },
    plan: 'Plano',
    amount: 'Valor',
    method: 'Forma de pagamento',
    date: 'Data',
    nextCharge: 'Próxima cobrança',
    order: 'Pedido',
    openApp: 'Abrir o Remoa',
    manage: 'Gerenciar assinatura',
    receipt: 'Este e-mail serve como seu comprovante. Para cancelar ou trocar de plano, use “Gerenciar assinatura”.',
  },
  passwordReset: {
    subject: 'Redefina sua senha do Remoa',
    preheader: 'O link vale por {expires}.',
    title: 'Vamos redefinir sua senha.',
    body: 'Recebemos um pedido para trocar a senha da conta {email}. Clique no botão para escolher uma nova.',
    button: 'Escolher nova senha',
    linkNote: 'O link vale por {expires} e só pode ser usado uma vez. Se o botão não funcionar, copie este endereço no navegador:',
    notYouBold: 'Não foi você?',
    notYou: ' Ignore este e-mail: sua senha continua a mesma. Se receber vários pedidos que você não fez, avise o suporte.',
    request: 'Pedido feito de {device} em {date}.',
    requestNoDevice: 'Pedido feito em {date}.',
  },
  calendar: {
    subjectD1: 'Amanhã: {title}',
    subjectD0: 'Hoje: {title} às {time}',
    subjectD0AllDay: 'Hoje: {title}',
    subjectMany: 'Amanhã você tem {count} compromissos',
    subjectManyD0: 'Hoje você tem {count} compromissos',
    titleManyD0: 'Hoje você tem {count} compromissos.',
    introManyD0: 'Olá, {name}. Aqui está o seu dia, {date}.',
    allDay: 'Dia inteiro',
    nameFallback: 'estudante',
    preheaderSingle: '{time} · {location}',
    preheaderSingleNoPlace: '{time}',
    titleD1: 'Amanhã tem {title}.',
    titleD0: 'É hoje: {title}.',
    titleMany: 'Amanhã você tem {count} compromissos.',
    introMany: 'Olá, {name}. Aqui está o seu dia de amanhã, {date}.',
    day: 'Dia',
    time: 'Horário',
    place: 'Local',
    cta: 'Ver no calendário',
    ics: 'Adicionar ao Google Agenda',
    dueCards: ['Você tem 1 card para revisar hoje.', 'Você tem {count} cards para revisar hoje.'],
    reviewNow: 'Revisar agora',
    moreItems: 'e mais {count}',
    coverAlt: 'Capa do compromisso {title}',
  },
  inactivity: {
    subject: 'Faz {days} dias que a gente não se vê',
    preheader: ['Retome em {minutes} minutos: 1 card espera por você.', 'Retome em {minutes} minutos: {cards} cards esperam por você.'],
    titleNoName: 'Seus mapas estão te esperando.',
    title: 'Seus mapas estão te esperando, {name}.',
    body: 'Faz {days} dias desde a sua última revisão. Sem pressão: com poucos minutos você retoma o ritmo.',
    statCards: ['card esperando', 'cards esperando'],
    statMaps: ['mapa', 'mapas'],
    nextAt: '{title}, {date}',
    statMinutes: '{minutes} min',
    statMinutesLabel: 'para retomar',
    next: 'Seu próximo compromisso:',
    resume: 'Retomar com {minutes} minutos',
    pause: 'Pausar estes lembretes',
    once: 'Enviamos este aviso uma vez por período de ausência.',
  },
  review: {
    subject: ['1 card espera por você hoje', '{cards} cards esperam por você hoje'],
    preheader: 'Cerca de {minutes} minutos para fixar o que vence hoje.',
    eyebrow: 'Revisão de hoje',
    big: ['card espera por você', 'cards esperam por você'],
    detail: '{due} e {new}. Cerca de {minutes} minutos.',
    due: ['1 vencido', '{count} vencidos'],
    new: ['1 novo', '{count} novos'],
    mapCards: ['1 card', '{count} cards'],
    cta: 'Começar revisão',
    note: 'Você escolhe o horário em Notificações. Só enviamos quando há cards para revisar.',
  },
  mapReady: {
    subject: 'Seu mapa “{map}” está pronto',
    preheader: '{cards} e {connections} para você revisar.',
    cardsN: ['1 card', '{count} cards'],
    connectionsN: ['1 conexão', '{count} conexões'],
    origin: { text: 'texto', pdf: 'PDF', anki: 'Anki' },
    title: 'Seu mapa “{map}” está pronto.',
    body: 'Montamos o mapa a partir do seu {source}. Ele já está na sua biblioteca.',
    cards: ['card', 'cards'],
    connections: ['conexão', 'conexões'],
    cta: 'Abrir meu mapa',
    warnBold: 'Revise antes de estudar.',
    warn: ' A IA pode errar. Cada card mostra a fonte e você pode corrigir o que precisar.',
  },
  waitlist: {
    subject: 'Você está na lista da Loja de mapas',
    preheader: 'Avisamos você quando a loja abrir.',
    title: 'Você está na lista.',
    body: 'Olá, {name}. Registramos o seu interesse na Loja de mapas.',
    bodyNoName: 'Olá. Registramos o seu interesse na Loja de mapas.',
    roles: { teacher: 'Professor', student_resident: 'Aluno ou residente', physician: 'Médico formado' },
    chipBuy: 'Quero comprar',
    chipSell: 'Quero vender · {profile}',
    chipSellNoProfile: 'Quero vender',
    whatNow: 'O que acontece agora',
    stepsBuy: [
      { title: 'Ainda não há data', text: 'A loja não está aberta e ainda não temos uma data.' },
      { title: 'Você é avisado primeiro', text: 'Mandamos um e-mail antes de todo mundo quando ela abrir.' },
    ],
    stepSell: { title: 'Vamos falar sobre vender', text: 'Entramos em contato antes sobre os primeiros vendedores.' },
    cta: 'Ver a Loja',
    meanwhile: 'Enquanto isso, os mapas prontos da equipe já estão na sua biblioteca.',
  },
  // CCR-035 (D-760): copy moved from apps/api/src/*/email-copy.ts, waitlist-copy.ts and store/copy.ts.
  hi: 'Oi, {name}.',
  hiNoName: 'Oi.',
  support: {
    subjectReceived: 'Chamado #{number} recebido',
    subjectAnswered: 'Resposta ao chamado #{number}',
    preheaderReceived: 'Nossa equipe vai analisar e responder em breve.',
    preheaderAnswered: 'A equipe respondeu. Leia a resposta no Remoa.',
    titleReceived: 'Recebemos seu chamado #{number}.',
    titleAnswered: 'Seu chamado #{number} tem resposta.',
    bodyReceived: 'Nossa equipe analisará em breve e responderá com a maior urgência possível.',
    bodyAnswered: 'A equipe respondeu ao seu chamado. Acesse o link abaixo para ler a resposta e continuar a conversa.',
    ctaReceived: 'Ver chamado',
    ctaAnswered: 'Ver resposta',
    reason: 'Você recebeu este e-mail porque abriu um chamado de suporte no Remoa.',
  },
  referralReward: {
    subject: '1 mês de Pro grátis para você!',
    preheader: 'Sua indicação foi qualificada.',
    titleReferrer: '{friend} criou o primeiro mapa.',
    bodyReferrer: 'Vocês dois ganharam 1 mês de Pro grátis! Acompanhe suas indicações no seu painel.',
    titleReferee: 'Seu primeiro mapa está pronto.',
    bodyReferee: 'Você e {friend} ganharam 1 mês de Pro grátis. Aproveite para revisar sem limites.',
    friendFallback: 'Seu amigo',
    friendFallbackLower: 'seu amigo',
    cta: 'Ver no painel',
    reason: 'Você recebeu este e-mail porque uma indicação sua foi qualificada. Desligue em Notificações quando quiser.',
  },
  referralInvite: {
    subject: '{referrer} convidou você para o Remoa',
    preheader: 'Vocês dois ganham 1 mês de Pro grátis.',
    title: '{referrer} convidou você para o Remoa.',
    body: 'O Remoa é um mapa de estudo que testa pelas conexões entre os conceitos. Quando você criar seu primeiro mapa pelo link abaixo, vocês dois ganham 1 mês de Pro grátis.',
    cta: 'Abrir convite',
    reason: 'Você recebeu este e-mail porque foi convidado para a plataforma.',
    stop: 'Não quero receber mais convites',
  },
  passwordChanged: {
    subject: 'Sua senha do Remoa foi alterada',
    preheader: 'Por segurança, encerramos a sessão nos outros dispositivos.',
    title: 'Sua senha foi alterada.',
    body: 'A senha da sua conta foi alterada em {date}. Por segurança, encerramos a sessão nos outros dispositivos.',
    notYouBold: 'Não foi você?',
    notYou: ' Redefina sua senha agora e responda este e-mail.',
    cta: 'Redefinir senha',
  },
  welcome: {
    subject: 'Boas-vindas ao Remoa',
    preheader: 'Comece pelo primeiro mapa, leva uns 5 minutos.',
    title: 'Boas-vindas ao Remoa, {name}.',
    titleNoName: 'Boas-vindas ao Remoa.',
    body: 'O Remoa é o seu mapa de estudo: cards conectados, revisão espaçada e desafios sobre o próprio mapa. Comece pelo primeiro mapa, leva uns 5 minutos.',
    cta: 'Abrir o Remoa',
  },
  onboardingNudge: {
    subjectFirstMap: 'Seu mapa está pronto para revisar',
    preheaderFirstMap: 'Veja a lembrança estimada de cada conceito.',
    titleFirstMap: 'Seu primeiro mapa cresceu.',
    bodyFirstMap: 'Seu primeiro mapa já passou de 20 cards. Revise agora e veja a lembrança estimada de cada conceito.',
    ctaFirstMap: 'Revisar agora',
    subjectDay3: 'Que tal fazer sua primeira sessão?',
    preheaderDay3: 'Uma revisão rápida já conta.',
    titleDay3: 'Que tal fazer sua primeira sessão?',
    bodyDay3: 'Já se passaram 3 dias e você ainda não fez uma sessão. Uma revisão rápida ou um desafio sobre o seu mapa já conta.',
    ctaDay3: 'Começar agora',
  },
  paymentReceipt: {
    subject: 'Seu recibo do Remoa',
    preheader: 'O recibo do seu pagamento no Remoa.',
    title: 'Seu recibo.',
    body: 'Aqui está o recibo do seu pagamento no Remoa.',
    cta: 'Ver recibo',
    reason: 'Você recebeu este e-mail porque a equipe reenviou o recibo de um pagamento seu.',
  },
  adminAlert: {
    subject: 'Alerta: exportação de dados',
    preheader: 'Verifique no painel se foi autorizada.',
    title: 'Exportação de dados registrada.',
    body: 'Uma exportação de {what} foi realizada em {date}. Verifique no painel de administração se foi autorizada.',
    users: ['1 usuário', '{count} usuários'],
    payments: ['1 transação', '{count} transações'],
    cta: 'Acessar painel',
    reason: 'Remoa Admin · Este e-mail é enviado sempre que dados são exportados.',
  },
  disputeResolved: {
    subject: 'Sua discordância foi revista',
    preheader: 'Um revisor registrou a decisão.',
    title: 'Sua discordância foi revista.',
    body: 'Um revisor registrou a decisão sobre a rubrica deste card.',
    cta: 'Abrir o Remoa',
  },
  landingWaitlist: {
    subject: 'Você está na lista de espera do Remoa',
    preheader: 'Avisaremos assim que sua vaga abrir.',
    title: 'Você está na lista.',
    body: 'Recebemos o seu e-mail e você está na lista de espera do Remoa. Avisaremos assim que sua vaga abrir.',
    notYou: 'Se não foi você, é só ignorar esta mensagem.',
    reason: 'Você recebeu este e-mail porque entrou na lista de espera do Remoa.',
  },
} as const;

/** [one, other]: picks by count and fills {count} (P-306). */
export const pl = (forms: readonly [string, string], count: number, vars: Record<string, string | number> = {}) =>
  fmt(count === 1 ? forms[0] : forms[1], { count, ...vars });

export function fmt(template: string, vars: Record<string, string | number> = {}): string {
  return template.replace(/\{(\w+)\}/g, (_, k: string) => String(vars[k] ?? ''));
}

export function hoursLabel(n: number): string {
  return n === 1 ? '1 hora' : `${n} horas`;
}

// pt-BR formatting of the raw contract values (cents, ISO instants, IANA timezone): callers never format.
const dtf = (timeZone: string, o: Intl.DateTimeFormatOptions) => new Intl.DateTimeFormat('pt-BR', { timeZone, ...o });
export const money = (cents: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(cents / 100);
/** "terça-feira, 6 de outubro" */
export const dateLong = (iso: string, tz: string) => dtf(tz, { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date(iso));
/** "1 de outubro de 2026" */
export const dateFull = (iso: string, tz: string) => dtf(tz, { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(iso));
/** "08:00" */
export const clock = (iso: string, tz: string) => dtf(tz, { hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).format(new Date(iso));
export const dateTime = (iso: string, tz: string) => `${dateFull(iso, tz)}, ${clock(iso, tz)}`;
/** Local calendar date "2026-10-06" → "terça-feira, 6 de outubro" (no timezone shift). */
export const localDateLong = (ymd: string) => dateLong(`${ymd}T12:00:00Z`, 'UTC');
